config/routes.rb
Rails.application.routes.draw do

   root 'welcome#index'

   get 'sign-up', to: 'registrations#new'
   post 'sign-up', to: 'registrations#create'
   get 'sign-out', to: 'authentication#destroy'
   get 'sign-in', to: 'authentication#new'
   post 'sign-in', to: 'authentication#create'

   get '/about', to: 'about#index'
   get '/terms', to: 'terms#index'
   get '/faq', to: 'common_questions#index'

   resources :users
   resources :tracker_projects, only:[:show]

   resources :projects do
     resources :tasks
     resources :memberships, only: [:index, :create, :update, :destroy]
   end

   resources :tasks, only: [] do
     resources :comments, only: [:create]
   end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  ROLE = ["Member", "Owner"]
  validates :user, presence: true
  validates :user, uniqueness: {scope: :project_id, message: "has already been added to this project" }
  validates :role, presence: true, inclusion:ROLE

  belongs_to :project
  belongs_to :user

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController

  before_action :authenticate_user
  before_action :set_project
  before_action :set_membership, only: [:update, :destroy]
  before_action :project_member_or_admin_authorization
  before_action :project_owner_or_admin_authorization, except: [:index]
  before_action :project_must_have_at_least_one_owner, only: [:update, :destroy]


  def index
     @membership = @project.memberships.new
   end

  def create
    @membership = @project.memberships.new(membership_params)
    if @membership.save
    flash[:success] = "#{@membership.user.full_name} was successfully added"
    redirect_to project_memberships_path
    else
      render :index
    end
  end

  def update
    if @membership.update(membership_params)
      flash[:success] = "#{@membership.user.full_name} was successfully updated"
      redirect_to project_memberships_path
    else
      render :index
    end
  end

  def destroy
    @membership.destroy
    flash[:success] = "#{@membership.user.full_name} was removed from project"
    redirect_to project_memberships_path
  end

  private

    def membership_params
      params.require(:membership).permit(:role, :project_id, :user_id)
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_membership
      @membership = Membership.find(params[:id])
    end

    def project_must_have_at_least_one_owner
      if @membership.role == 'Owner' && @project.memberships.where(role: 'Owner').count <= 1
        flash[:danger] = "Projects must have at least one owner"
        redirect_to project_memberships_path(@project)
      end
    end

 end

app/views/memberships/index.html.erb
<div class="container">

  <div class="page-header">
    <h1>
      <%= @project.name %>: Manage Members
    </h1>
  </div>

  <ol class="breadcrumb">
    <li><%= link_to 'Projects', projects_path(@projects) %></li>
    <li><%= link_to @project.name, project_path(@project) %></li>
    <li class="active">Memberships</li>
  </ol>

  <div class= "row">
    <div class= "col-md-8">
      <%= render partial: "shared/errors", locals: {object: @membership} %>
    </div>
  </div>

  <% if current_user.project_owner_verify(@project) %>
  <div class="row">
    <%= form_for [@project, @membership], html: {class: "form-inline" } do |f| %>
      <div class='col-md-8'>
        <div class='well'>
          <%= f.collection_select(:user_id, User.all, :id, :full_name, {prompt: "please select a user..."},{class: 'form-control'}) %>
          <%= f.collection_select(:role, Membership::ROLE, :to_s, :to_s, {},{class: 'form-control'}) %>
          <%= f.submit "Add New Member", class: 'btn btn-primary' %>
        </div>
      </div>
     <% end %>
    </div>
  <% end %>
    <br />
    <div class= "row col-sm-8">
      <table class= "table">
        <% @project.memberships.each do |membership| %>
          <%if membership.id && membership.user.present? %>
            <%= form_for [@project, membership], html: {class: "form-inline"} do |f| %>
              <tbody>
                <tr>
                  <td><%= link_to membership.user.full_name, user_path(membership.user) %></td>
                  <% if current_user.project_owner_verify(@project) %>
                    <td><%= f.collection_select(:role, Membership::ROLE, :to_s, :to_s, {prompt: membership.role}, {class:'form-control'}) %></td>
                    <td><%= f.submit "Update", class: "btn btn-primary" %></td>
                  <% end %>

                  <% if current_user.project_owner_verify(@project) || current_user.id == membership.user_id %>
                    <% if @project.memberships.where(role: "Owner").count == 1 && membership.role == "Owner" %>
                      <td>You are the last owner</td>
                    <% else %>
                      <td><%= link_to "",project_membership_path(@project, membership), method: :delete, class: "glyphicon glyphicon-remove"%><td>
                    <% end %>
                  <% else %>
                    <td></td>
                    <td></td>
                  <% end %>
                </tr>
              </tbody>
          <% end %>
        <% end %>
      <% end %>
    </table>
  </div>
</div>