config/routes.rb
Rails.application.routes.draw do

   root 'welcome#index'

   get 'sign-up', to: 'registrations#new'
   post 'sign-up', to: 'registrations#create'
   get 'sign-out', to: 'authentication#destroy'
   get 'sign-in', to: 'authentication#new'
   post 'sign-in', to: 'authentication#create'

   get '/about', to: 'about#index'
   get '/terms', to: 'terms#index'
   get '/faq', to: 'common_questions#index'

   resources :users
   resources :tracker_projects, only:[:show]

   resources :projects do
     resources :tasks
     resources :memberships, only: [:index, :create, :update, :destroy]
   end

   resources :tasks, only: [] do
     resources :comments, only: [:create]
   end
end

app/models/task.rb
class Task < ActiveRecord::Base

  validates :description, presence: true

  belongs_to :project

  has_many :comments, dependent: :destroy

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :target_project
  before_action :authenticate_user
  before_action :project_member_or_admin_authorization


  before_action do
    @project = Project.find(params[:project_id])
  end

  def index
    @tasks = @project.tasks
  end

  def new
    @task = Task.new
  end

  def create
    @task = @project.tasks.new(task_params)
    if @task.save
      flash[:success] = "Task was successfully created"
      redirect_to project_task_path(@project, @task)
    else
      render :new
    end
  end

  def show
    @task = Task.find(params[:id])
    @comment = Comment.new
    @comments = @task.comments
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      flash[:success] = "Task was successfully updated"
      redirect_to project_task_path(@project, @task)
    else
      render :edit
    end
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to project_tasks_path
  end


  private

  def task_params
    params.require(:task).permit(:description, :complete, :due_date, :project_id)
  end

  def target_project
    @project = Project.find(params[:project_id])
  end

end

app/views/tasks/_form.html.erb
<div class="form-horizontal">

 <%= form_for [@project, @task] do |f| %>


   <div class="form-group">
     <%= f.label :description, class: "col-md-2 control-label" %>
     <div class="col-md-5">
       <%= f.text_field :description, class: "form-control", placeholder: "Description" %>
     </div>
   </div>

   <div class="form-group">
     <%= f.label :due_date, class: "col-md-2 control-label" %>
     <div class="col-md-2">
       <%= f.date_field :due_date, class: "col-md-2 form-control", placeholder: "Due Date" %>
     </div>
   </div>

   <% unless @task.new_record? %>
     <div class="form-group">
       <div class="col-md-offset-2 col-sm-6">
         <%= f.check_box :complete %>
         <%= f.label :complete %>
       </div>
     </div>
   <% end %>


   <div class="form-group">
     <div class="col-md-offset-2 col-sm-6">
       <%= f.submit class: "btn btn-primary"%>
       <%= link_to "Cancel", project_tasks_path, class: "btn btn-default" %>
     </div>
   </div>
 <% end %>
</div>

app/views/tasks/edit.html.erb
<div class= "container">
  <h1>Edit Task</h1>

  <br />

  <div>
    <ol class="breadcrumb">
      <li><%= link_to "Projects", projects_path %></li>
      <li><%= link_to @project.name, project_path(@project) %>
      <li><%=link_to "Tasks", project_tasks_path %></li>
      <li class="active">Edit</li>
    </ol>
  </div>

    <%= render partial: "shared/errors", locals: {object: @task} %>
    <%= render partial: "form", locals: {button_name: "Update Task"} %>

  <br/>
</div>

app/views/tasks/index.html.erb
<div class= "container">
  <div class="page-header">
    <div class="pull-right">
      <%= link_to "New Task", new_project_task_path, class: "btn btn-info" %>
    </div>
      <h1>Tasks for <%= @project.name %></h1>
    </div>

    <ol class="breadcrumb">
      <li><%= link_to "Projects", projects_path %></li>
      <li><%= link_to @project.name, project_path(@project) %></li>
      <li class="active">Tasks</li>
    </ol>

      <table class="table">
        <thead>
          <tr>
            <th>Description</th>
            <th>Due On</th>
          </tr>
        </thead>
        <% @tasks.each do |task| %>
          <tr>
            <td>
              <% if task.complete == true %>
                <s><%= link_to task.description, project_task_path(params[:project_id], task) %></s>
              <% else %>
                <%= link_to task.description, project_task_path(params[:project_id], task) %>
                 <div class="badge">
                   <%= task.comments.count %>
                 </div>
              <% end %>
            </td>
            <td>
              <div class= "text-left">
                <% if task.due_date %>
                  <%= task.due_date.strftime("%m/%d/%Y") %>
                <% end %>
              </div>
            </td>
            <td>
              <div class= "text-right">
                <%= link_to "Edit", edit_project_task_path(params[:project_id], task), class: "btn btn-info" %>
                <%= link_to "", project_task_path(params[:project_id], task), method: :delete, class: "glyphicon glyphicon-remove", data: { confirm: "Are you sure?" }  %>
              </div>
            </td>
            <% end %>
          </tr>
    </table>
</div>

app/views/tasks/new.html.erb
<div class= "container">
    <div class="page-header">
      <h1>New Task</h1>
    </div>

  <div>
     <ol class="breadcrumb">
       <li><%= link_to "Projects", projects_path %></li>
       <li><%= link_to @project.name, project_path(@project) %>
       <li><%=link_to "Tasks", project_tasks_path %></li>
       <li class="active">New Task</li>
     </ol>
  </div>
  <%= render partial: "shared/errors", locals: {object: @task} %>

  <%= render partial: "form", locals: {button_name: "Create Task"} %>
</div>

app/views/tasks/show.html.erb
<div class= "container">
  <div class="page-header">
    <h1>
      <% if @task.complete == true %>
        <s><%= @task.description %></s>
      <% else %>
        <%= @task.description %>
      <% end %>
      <div class="pull-right">
        <%= link_to "Edit", edit_project_task_path(@project, @task), class: "btn btn-info" %>
      </div>
    </h1>
  </div>

  <ol class="breadcrumb">
    <li><%= link_to "Projects", projects_path %></li>
    <li><%= link_to @project.name, project_path(@project) %></li>
    <li><%= link_to "Tasks", project_tasks_path(@project) %>
    <li class="active"><%= @task.description %></li>
  </ol>

  <p>
    <strong>
      Due On:
    </strong>
    <% if @task.due_date %>
      <%= @task.due_date.strftime("%m/%d/%Y") %>
    <% end %>
  </p>


  <p>
    <h3>Comments</h3>
  </p>
    <% @task.comments.each do |comment| %>
      <p>
        <div class= "row">
          <div class= "col-md-3">
            <% if comment.user == nil %>
            <%= "(deleted user)" %>
            <% else %>
            <%= link_to comment.user.full_name, user_path(comment.user) %>
            <% end %>
            <div class= "text-muted">
              <%= "#{time_ago_in_words(comment.created_at)} ago" %>
            </div>
          </div>
          <div class= "col-md-9">
            <%= comment.content %>
          </div>
        </div>
      </p>
    <% end %>

    <%= form_for [@task, @comment], html: {class: "form-group"} do |f| %>
    <p>
    <div class= "row">
      <div class= "col-md-offset-3">
        <div class= "col-md-9">
          <%= f.text_area :content, class: "form-control" %>
        </div>
      </div>
    </div>
    </p>

    <p>
    <div class= "row">
      <div class= "col-md-offset-3 col-md-9">
        <%= f.submit "Add Comment", class: "btn btn-primary" %>
      </div>
    </div>
    </p>
  <%end%>
</div>