config/routes.rb
Rails.application.routes.draw do

   root 'welcome#index'

   get 'sign-up', to: 'registrations#new'
   post 'sign-up', to: 'registrations#create'
   get 'sign-out', to: 'authentication#destroy'
   get 'sign-in', to: 'authentication#new'
   post 'sign-in', to: 'authentication#create'

   get '/about', to: 'about#index'
   get '/terms', to: 'terms#index'
   get '/faq', to: 'common_questions#index'

   resources :users
   resources :tracker_projects, only:[:show]

   resources :projects do
     resources :tasks
     resources :memberships, only: [:index, :create, :update, :destroy]
   end

   resources :tasks, only: [] do
     resources :comments, only: [:create]
   end
end

app/models/project.rb
class Project < ActiveRecord::Base

  validates :name, presence: true

  has_many :tasks, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user
  before_action :target_project, except: [:new, :create, :index]
  before_action :project_member_or_admin_authorization, except: [:new, :create, :index]
  before_action :project_owner_or_admin_authorization, only: [:edit, :update, :destroy]

  def index
    @project = Project.all
    tracker_api = TrackerAPI.new
    if current_user.pivotal_tracker_token
      if tracker_api.projects(current_user.pivotal_tracker_token).class == Array
      @tracker_projects = tracker_api.projects(current_user.pivotal_tracker_token)
      else
        flash[:danger] = "Looks like you have an invalid Pivotal Tracker Token.  Please update to view your connected projects"
        @tracker_projects = {}
      end
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      ProjectManagement.assign_current_user_as_project_owner(@project, current_user)
      flash[:success] = "Project was successfully created"
      redirect_to project_tasks_path(@project)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update(project_params)
      flash[:success] = "Project was successfully updated"
      redirect_to projects_path
    else
      render :edit
    end
  end

  def destroy
    if @project.destroy
      flash[:success] = "Project was successfully deleted"
      redirect_to projects_path
    else
      render :edit
    end
  end

  private

    def project_params
      params.require(:project).permit(:name)
    end

    def target_project
      @project = Project.find(params[:id])
    end

end

app/views/projects/_form.html.erb
<div class="form-horizontal">

  <%= form_for @project do |f| %>

  <div class="form-group">
    <%= f.label :name, class: "col-md-2 control-label" %>
    <div class="col-md-5">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-sm-6">
      <%= f.submit class: "btn btn-primary"%>
      <%= link_to "Cancel", projects_path, class: "btn btn-default" %>
    </div>
  </div>
<% end %>
</div>

app/views/projects/edit.html.erb
<div class="container">
  <div class="page-header">
    <h1>Edit Project</h1>
  </div>
  <%= render partial: "shared/errors", locals: {object: @project} %>

  <ol class="breadcrumb">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Projects", projects_path %></li>
    <li><%= link_to @project.name, project_path(@project) %></li>
    <li class="active">Edit</li>
  </ol>
  <%= render partial: "form", locals: {button_name: "Update Project"} %>

</div>

app/views/projects/index.html.erb
<div class="container">
  <div class="page-header">
    <div class="top_header">
      <div class="pull-right">
        <%= link_to "New Project", new_project_path, class: "btn btn-info" %>
      </div>
      <h1>Projects</h1>
    </div>

    <table class='table'>
      <thead>
        <tr>
          <th><strong>Name</strong></th>
          <th><stong>Tasks</strong></th>
        </tr>
      </thead>

      <% if current_user.admin  %>
        <% @project.each do |project| %>
        <tr>
          <td><%= link_to project.name, project_path(project) %></td>
          <td><%= link_to project.tasks.count, project_tasks_path(project) %></td>
        </tr>
        <% end %>
      <% else %>
        <% current_user.projects.each do |project| %>
        <tr>
          <td><%= link_to project.name, project_path(project) %></td>
          <td><%= link_to project.tasks.count, project_tasks_path(project) %></td>
        </tr>
        <% end %>
      <% end %>
    </table>
  </div>

  <div class="page-header">
    <div class="pull-right">
    </div>
    <h1>Pivotal Tracker Projects</h1>
  </div>

  <table class='table'>
    <thead>
      <tr>
        <th><strong>Name</strong></th>
      </tr>
    </thead>
      <% if current_user.pivotal_tracker_token %>
        <% @tracker_projects.each do |project| %>
        <tr>
          <td><%= link_to project[:name], tracker_project_path(project[:id],project_name: project[:name]) %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="page-header">
    <h1>New Project</h1>
  </div>
  <%= render partial: "shared/errors", locals: {object: @project} %>

  <ol class="breadcrumb">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Projects", projects_path %></li>
    <li class="active">New Project</li>
  </ol>

  <%= render partial: "form", locals: {button_name: "Create Project"} %>

</div>

app/views/projects/show.html.erb
<div class="container">
  <div class="page-header">
    <div class="pull-right">
      <% if current_user.project_owner_verify(@project) || current_user.admin %>
      <div class= 'pull-right'>
        <%= link_to 'Edit', edit_project_path(@project), class: 'btn btn-info'%>
      </div>
      <% end %>
  </div>
    <h1><%= @project.name %></h1>
  </div>

  <ol class="breadcrumb">
    <li><%= link_to "Projects", projects_path %></li>
    <li class="active"><%= @project.name %></li>
  </ol>

  <p><%= link_to "#{pluralize(@project.tasks.count, "Task")}", project_tasks_path(@project) %></p>

  <p><%= link_to "#{pluralize(@project.memberships.count, "Membership")}", project_memberships_path(@project) %></p>

  <% if current_user.project_owner_verify(@project) || current_user.admin %>
    <div class="well">
      <h4>Delete Project</h4>
        <p> <%= "Deleting this project will also delete #{pluralize(@project.memberships.count, 'membership') },
          #{pluralize(@project.tasks.count, 'task') } and associated comments" %></p>
        <%= link_to 'Delete', project_path(@project), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger' %>
      </div>
  <% end %>
</div>